/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as OraculoRouteImport } from './routes/oraculo'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CartaAstralRouteImport } from './routes/carta-astral'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunasIndexRouteImport } from './routes/runas.index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as RunasSlugRouteImport } from './routes/runas.$slug'
import { Route as BibliotecaSlugRouteImport } from './routes/biblioteca.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const OraculoRoute = OraculoRouteImport.update({
  id: '/oraculo',
  path: '/oraculo',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaAstralRoute = CartaAstralRouteImport.update({
  id: '/carta-astral',
  path: '/carta-astral',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunasIndexRoute = RunasIndexRouteImport.update({
  id: '/runas/',
  path: '/runas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/biblioteca/',
  path: '/biblioteca/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunasSlugRoute = RunasSlugRouteImport.update({
  id: '/runas/$slug',
  path: '/runas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaSlugRoute = BibliotecaSlugRouteImport.update({
  id: '/biblioteca/$slug',
  path: '/biblioteca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carta-astral': typeof CartaAstralRoute
  '/legal': typeof LegalRoute
  '/oraculo': typeof OraculoRoute
  '/privacidad': typeof PrivacidadRoute
  '/productos': typeof ProductosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/runas/$slug': typeof RunasSlugRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/runas/': typeof RunasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carta-astral': typeof CartaAstralRoute
  '/legal': typeof LegalRoute
  '/oraculo': typeof OraculoRoute
  '/privacidad': typeof PrivacidadRoute
  '/productos': typeof ProductosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/runas/$slug': typeof RunasSlugRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/runas': typeof RunasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carta-astral': typeof CartaAstralRoute
  '/legal': typeof LegalRoute
  '/oraculo': typeof OraculoRoute
  '/privacidad': typeof PrivacidadRoute
  '/productos': typeof ProductosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/runas/$slug': typeof RunasSlugRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/runas/': typeof RunasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carta-astral'
    | '/legal'
    | '/oraculo'
    | '/privacidad'
    | '/productos'
    | '/sitemap.xml'
    | '/sobre'
    | '/biblioteca/$slug'
    | '/runas/$slug'
    | '/biblioteca/'
    | '/runas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carta-astral'
    | '/legal'
    | '/oraculo'
    | '/privacidad'
    | '/productos'
    | '/sitemap.xml'
    | '/sobre'
    | '/biblioteca/$slug'
    | '/runas/$slug'
    | '/biblioteca'
    | '/runas'
  id:
    | '__root__'
    | '/'
    | '/carta-astral'
    | '/legal'
    | '/oraculo'
    | '/privacidad'
    | '/productos'
    | '/sitemap.xml'
    | '/sobre'
    | '/biblioteca/$slug'
    | '/runas/$slug'
    | '/biblioteca/'
    | '/runas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartaAstralRoute: typeof CartaAstralRoute
  LegalRoute: typeof LegalRoute
  OraculoRoute: typeof OraculoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ProductosRoute: typeof ProductosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  BibliotecaSlugRoute: typeof BibliotecaSlugRoute
  RunasSlugRoute: typeof RunasSlugRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  RunasIndexRoute: typeof RunasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oraculo': {
      id: '/oraculo'
      path: '/oraculo'
      fullPath: '/oraculo'
      preLoaderRoute: typeof OraculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta-astral': {
      id: '/carta-astral'
      path: '/carta-astral'
      fullPath: '/carta-astral'
      preLoaderRoute: typeof CartaAstralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runas/': {
      id: '/runas/'
      path: '/runas'
      fullPath: '/runas/'
      preLoaderRoute: typeof RunasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runas/$slug': {
      id: '/runas/$slug'
      path: '/runas/$slug'
      fullPath: '/runas/$slug'
      preLoaderRoute: typeof RunasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$slug': {
      id: '/biblioteca/$slug'
      path: '/biblioteca/$slug'
      fullPath: '/biblioteca/$slug'
      preLoaderRoute: typeof BibliotecaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartaAstralRoute: CartaAstralRoute,
  LegalRoute: LegalRoute,
  OraculoRoute: OraculoRoute,
  PrivacidadRoute: PrivacidadRoute,
  ProductosRoute: ProductosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  BibliotecaSlugRoute: BibliotecaSlugRoute,
  RunasSlugRoute: RunasSlugRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  RunasIndexRoute: RunasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
